import { defineComponent, provide } from 'vue';

import OfficersService from './officers/officers.service';
import DepartmentService from './department/department.service';
import RoleService from './role/role.service';
import PermissionService from './permission/permission.service';
import ProjectService from './project/project.service';
import PlanstrategyService from './planstrategy/planstrategy.service';
import ComprehensivecontrolService from './comprehensivecontrol/comprehensivecontrol.service';
import DocumentService from './document/document.service';
import ComprehensiveledgerService from './comprehensiveledger/comprehensiveledger.service';
import CycleplanService from './cycleplan/cycleplan.service';
import AnnualplanService from './annualplan/annualplan.service';
import MonthplanService from './monthplan/monthplan.service';
import PlanreturnsService from './planreturns/planreturns.service';
import PlanmonitorService from './planmonitor/planmonitor.service';
import PlanexecuteService from './planexecute/planexecute.service';
import ProjectchargeService from './projectcharge/projectcharge.service';
import PbsmanageService from './pbsmanage/pbsmanage.service';
import PbssubmanageService from './pbssubmanage/pbssubmanage.service';
import WbsmanageService from './wbsmanage/wbsmanage.service';
import WbssubmanageService from './wbssubmanage/wbssubmanage.service';
import PbsbaselineService from './pbsbaseline/pbsbaseline.service';
import WbsbaselineService from './wbsbaseline/wbsbaseline.service';
import ProgressmanagementService from './progressmanagement/progressmanagement.service';
import QualitymanagementService from './qualitymanagement/qualitymanagement.service';
import QualityobjectivesService from './qualityobjectives/qualityobjectives.service';
import QualityreturnsService from './qualityreturns/qualityreturns.service';
import UnQualityAuditService from './un-quality-audit/un-quality-audit.service';
import FundsmanagementService from './fundsmanagement/fundsmanagement.service';
import TotalbudgetService from './totalbudget/totalbudget.service';
import UnitbudgetService from './unitbudget/unitbudget.service';
import FundsavailabilityService from './fundsavailability/fundsavailability.service';
import ContractualfundsService from './contractualfunds/contractualfunds.service';
import OutsourcingmPurchasePlanService from './outsourcingm-purchase-plan/outsourcingm-purchase-plan.service';
import OutsourcingmPurchaseExecuteService from './outsourcingm-purchase-execute/outsourcingm-purchase-execute.service';
import ResourcemanagementService from './resourcemanagement/resourcemanagement.service';
import HumanresourcesService from './humanresources/humanresources.service';
import TechnicalConditionService from './technical-condition/technical-condition.service';
import RiskmanagementService from './riskmanagement/riskmanagement.service';
import RiskreportService from './riskreport/riskreport.service';
import SecrecymanagementService from './secrecymanagement/secrecymanagement.service';
import ProjectSecrecyService from './project-secrecy/project-secrecy.service';
import AnnualSecurityPlanService from './annual-security-plan/annual-security-plan.service';
import SafetycheckService from './safetycheck/safetycheck.service';
import EvaluationCriteriaService from './evaluation-criteria/evaluation-criteria.service';
import ManagementCapacityEvaluationService from './management-capacity-evaluation/management-capacity-evaluation.service';
import ApprovalAgentService from './approval-agent/approval-agent.service';
import UserService from '@/entities/user/user.service';
// jhipster-needle-add-entity-service-to-entities-component-import - JHipster will import entities services here

export default defineComponent({
  compatConfig: { MODE: 3 },
  name: 'Entities',
  setup() {
    provide('userService', () => new UserService());
    provide('officersService', () => new OfficersService());
    provide('departmentService', () => new DepartmentService());
    provide('roleService', () => new RoleService());
    provide('permissionService', () => new PermissionService());
    provide('projectService', () => new ProjectService());
    provide('planstrategyService', () => new PlanstrategyService());
    provide('comprehensivecontrolService', () => new ComprehensivecontrolService());
    provide('documentService', () => new DocumentService());
    provide('comprehensiveledgerService', () => new ComprehensiveledgerService());
    provide('cycleplanService', () => new CycleplanService());
    provide('annualplanService', () => new AnnualplanService());
    provide('monthplanService', () => new MonthplanService());
    provide('planreturnsService', () => new PlanreturnsService());
    provide('planmonitorService', () => new PlanmonitorService());
    provide('planexecuteService', () => new PlanexecuteService());
    provide('projectchargeService', () => new ProjectchargeService());
    provide('pbsmanageService', () => new PbsmanageService());
    provide('pbssubmanageService', () => new PbssubmanageService());
    provide('wbsmanageService', () => new WbsmanageService());
    provide('wbssubmanageService', () => new WbssubmanageService());
    provide('pbsbaselineService', () => new PbsbaselineService());
    provide('wbsbaselineService', () => new WbsbaselineService());
    provide('progressmanagementService', () => new ProgressmanagementService());
    provide('qualitymanagementService', () => new QualitymanagementService());
    provide('qualityobjectivesService', () => new QualityobjectivesService());
    provide('qualityreturnsService', () => new QualityreturnsService());
    provide('unQualityAuditService', () => new UnQualityAuditService());
    provide('fundsmanagementService', () => new FundsmanagementService());
    provide('totalbudgetService', () => new TotalbudgetService());
    provide('unitbudgetService', () => new UnitbudgetService());
    provide('fundsavailabilityService', () => new FundsavailabilityService());
    provide('contractualfundsService', () => new ContractualfundsService());
    provide('outsourcingmPurchasePlanService', () => new OutsourcingmPurchasePlanService());
    provide('outsourcingmPurchaseExecuteService', () => new OutsourcingmPurchaseExecuteService());
    provide('resourcemanagementService', () => new ResourcemanagementService());
    provide('humanresourcesService', () => new HumanresourcesService());
    provide('technicalConditionService', () => new TechnicalConditionService());
    provide('riskmanagementService', () => new RiskmanagementService());
    provide('riskreportService', () => new RiskreportService());
    provide('secrecymanagementService', () => new SecrecymanagementService());
    provide('projectSecrecyService', () => new ProjectSecrecyService());
    provide('annualSecurityPlanService', () => new AnnualSecurityPlanService());
    provide('safetycheckService', () => new SafetycheckService());
    provide('evaluationCriteriaService', () => new EvaluationCriteriaService());
    provide('managementCapacityEvaluationService', () => new ManagementCapacityEvaluationService());
    provide('approvalAgentService', () => new ApprovalAgentService());
    // jhipster-needle-add-entity-service-to-entities-component - JHipster will import entities services here
  },
});
