import { defineComponent, provide } from 'vue';

import OfficersService from './officers/officers.service';
import DepartmentService from './department/department.service';
import RoleService from './role/role.service';
import PermissionService from './permission/permission.service';
import ProjectService from './project/project.service';
import ProjectwbsService from './projectwbs/projectwbs.service';
import IntegratedmanagementService from './integratedmanagement/integratedmanagement.service';
import IntegratedmanagementWbsService from './integratedmanagement-wbs/integratedmanagement-wbs.service';
import PlanstrategyService from './planstrategy/planstrategy.service';
import ComprehensivecontrolService from './comprehensivecontrol/comprehensivecontrol.service';
import DocumentService from './document/document.service';
import ComprehensiveledgerService from './comprehensiveledger/comprehensiveledger.service';
import CycleplanService from './cycleplan/cycleplan.service';
import AnnualplanService from './annualplan/annualplan.service';
import MonthplanService from './monthplan/monthplan.service';
import PlanreturnsService from './planreturns/planreturns.service';
import PlanmonitorService from './planmonitor/planmonitor.service';
import PlanexecuteService from './planexecute/planexecute.service';
import ProjectchargeService from './projectcharge/projectcharge.service';
import PbsmanageService from './pbsmanage/pbsmanage.service';
import PbssubmanageService from './pbssubmanage/pbssubmanage.service';
import WbsmanageService from './wbsmanage/wbsmanage.service';
import WbssubmanageService from './wbssubmanage/wbssubmanage.service';
import PbsbaselineService from './pbsbaseline/pbsbaseline.service';
import WbsbaselineService from './wbsbaseline/wbsbaseline.service';
import ProgressmanagementService from './progressmanagement/progressmanagement.service';
import ProgressmanagementWbsService from './progressmanagement-wbs/progressmanagement-wbs.service';
import ProgressplanService from './progressplan/progressplan.service';
import ProgressplanreturnsService from './progressplanreturns/progressplanreturns.service';
import ProgressbaselineService from './progressbaseline/progressbaseline.service';
import QualitymanagementService from './qualitymanagement/qualitymanagement.service';
import QualitymanagementWbsService from './qualitymanagement-wbs/qualitymanagement-wbs.service';
import QualityobjectivesService from './qualityobjectives/qualityobjectives.service';
import QualityreturnsService from './qualityreturns/qualityreturns.service';
import UnQualityAuditService from './un-quality-audit/un-quality-audit.service';
import FundsmanagementService from './fundsmanagement/fundsmanagement.service';
import FundsmanagementWbsService from './fundsmanagement-wbs/fundsmanagement-wbs.service';
import AuditedbudgetService from './auditedbudget/auditedbudget.service';
import TotalbudgetService from './totalbudget/totalbudget.service';
import UnitbudgetService from './unitbudget/unitbudget.service';
import FundsavailabilityService from './fundsavailability/fundsavailability.service';
import ContractualfundsService from './contractualfunds/contractualfunds.service';
import OutsourcingmanagementService from './outsourcingmanagement/outsourcingmanagement.service';
import OutsourcingmanagementWbsService from './outsourcingmanagement-wbs/outsourcingmanagement-wbs.service';
import OutsourcingPurchasePlanService from './outsourcing-purchase-plan/outsourcing-purchase-plan.service';
import OutsourcingPurchaseExecuteService from './outsourcing-purchase-execute/outsourcing-purchase-execute.service';
import ResourcemanagementService from './resourcemanagement/resourcemanagement.service';
import ResourcemanagementWbsService from './resourcemanagement-wbs/resourcemanagement-wbs.service';
import ProjectHumanresourcesplanService from './project-humanresourcesplan/project-humanresourcesplan.service';
import ProjectremitService from './projectremit/projectremit.service';
import HumanresourcesService from './humanresources/humanresources.service';
import TechnicalmanagementService from './technicalmanagement/technicalmanagement.service';
import TechnicalmanagementWbsService from './technicalmanagement-wbs/technicalmanagement-wbs.service';
import TechnicalConditionService from './technical-condition/technical-condition.service';
import RiskmanagementService from './riskmanagement/riskmanagement.service';
import RiskmanagementWbsService from './riskmanagement-wbs/riskmanagement-wbs.service';
import RiskidentificationService from './riskidentification/riskidentification.service';
import RiskreportService from './riskreport/riskreport.service';
import SecrecymanagementService from './secrecymanagement/secrecymanagement.service';
import SecrecymanagementWbsService from './secrecymanagement-wbs/secrecymanagement-wbs.service';
import SecrecysystemService from './secrecysystem/secrecysystem.service';
import ProjectSecrecyService from './project-secrecy/project-secrecy.service';
import SecuritymanagementService from './securitymanagement/securitymanagement.service';
import SecuritymanagementWbsService from './securitymanagement-wbs/securitymanagement-wbs.service';
import AnnualSecurityPlanService from './annual-security-plan/annual-security-plan.service';
import SafetycheckService from './safetycheck/safetycheck.service';
import EvaluationCriteriaService from './evaluation-criteria/evaluation-criteria.service';
import ManagementCapacityEvaluationService from './management-capacity-evaluation/management-capacity-evaluation.service';
import ApprovalAgentService from './approval-agent/approval-agent.service';
import UserService from '@/entities/user/user.service';
// jhipster-needle-add-entity-service-to-entities-component-import - JHipster will import entities services here

export default defineComponent({
  compatConfig: { MODE: 3 },
  name: 'Entities',
  setup() {
    provide('userService', () => new UserService());
    provide('officersService', () => new OfficersService());
    provide('departmentService', () => new DepartmentService());
    provide('roleService', () => new RoleService());
    provide('permissionService', () => new PermissionService());
    provide('projectService', () => new ProjectService());
    provide('projectwbsService', () => new ProjectwbsService());
    provide('integratedmanagementService', () => new IntegratedmanagementService());
    provide('integratedmanagementWbsService', () => new IntegratedmanagementWbsService());
    provide('planstrategyService', () => new PlanstrategyService());
    provide('comprehensivecontrolService', () => new ComprehensivecontrolService());
    provide('documentService', () => new DocumentService());
    provide('comprehensiveledgerService', () => new ComprehensiveledgerService());
    provide('cycleplanService', () => new CycleplanService());
    provide('annualplanService', () => new AnnualplanService());
    provide('monthplanService', () => new MonthplanService());
    provide('planreturnsService', () => new PlanreturnsService());
    provide('planmonitorService', () => new PlanmonitorService());
    provide('planexecuteService', () => new PlanexecuteService());
    provide('projectchargeService', () => new ProjectchargeService());
    provide('pbsmanageService', () => new PbsmanageService());
    provide('pbssubmanageService', () => new PbssubmanageService());
    provide('wbsmanageService', () => new WbsmanageService());
    provide('wbssubmanageService', () => new WbssubmanageService());
    provide('pbsbaselineService', () => new PbsbaselineService());
    provide('wbsbaselineService', () => new WbsbaselineService());
    provide('progressmanagementService', () => new ProgressmanagementService());
    provide('progressmanagementWbsService', () => new ProgressmanagementWbsService());
    provide('progressplanService', () => new ProgressplanService());
    provide('progressplanreturnsService', () => new ProgressplanreturnsService());
    provide('progressbaselineService', () => new ProgressbaselineService());
    provide('qualitymanagementService', () => new QualitymanagementService());
    provide('qualitymanagementWbsService', () => new QualitymanagementWbsService());
    provide('qualityobjectivesService', () => new QualityobjectivesService());
    provide('qualityreturnsService', () => new QualityreturnsService());
    provide('unQualityAuditService', () => new UnQualityAuditService());
    provide('fundsmanagementService', () => new FundsmanagementService());
    provide('fundsmanagementWbsService', () => new FundsmanagementWbsService());
    provide('auditedbudgetService', () => new AuditedbudgetService());
    provide('totalbudgetService', () => new TotalbudgetService());
    provide('unitbudgetService', () => new UnitbudgetService());
    provide('fundsavailabilityService', () => new FundsavailabilityService());
    provide('contractualfundsService', () => new ContractualfundsService());
    provide('outsourcingmanagementService', () => new OutsourcingmanagementService());
    provide('outsourcingmanagementWbsService', () => new OutsourcingmanagementWbsService());
    provide('outsourcingPurchasePlanService', () => new OutsourcingPurchasePlanService());
    provide('outsourcingPurchaseExecuteService', () => new OutsourcingPurchaseExecuteService());
    provide('resourcemanagementService', () => new ResourcemanagementService());
    provide('resourcemanagementWbsService', () => new ResourcemanagementWbsService());
    provide('projectHumanresourcesplanService', () => new ProjectHumanresourcesplanService());
    provide('projectremitService', () => new ProjectremitService());
    provide('humanresourcesService', () => new HumanresourcesService());
    provide('technicalmanagementService', () => new TechnicalmanagementService());
    provide('technicalmanagementWbsService', () => new TechnicalmanagementWbsService());
    provide('technicalConditionService', () => new TechnicalConditionService());
    provide('riskmanagementService', () => new RiskmanagementService());
    provide('riskmanagementWbsService', () => new RiskmanagementWbsService());
    provide('riskidentificationService', () => new RiskidentificationService());
    provide('riskreportService', () => new RiskreportService());
    provide('secrecymanagementService', () => new SecrecymanagementService());
    provide('secrecymanagementWbsService', () => new SecrecymanagementWbsService());
    provide('secrecysystemService', () => new SecrecysystemService());
    provide('projectSecrecyService', () => new ProjectSecrecyService());
    provide('securitymanagementService', () => new SecuritymanagementService());
    provide('securitymanagementWbsService', () => new SecuritymanagementWbsService());
    provide('annualSecurityPlanService', () => new AnnualSecurityPlanService());
    provide('safetycheckService', () => new SafetycheckService());
    provide('evaluationCriteriaService', () => new EvaluationCriteriaService());
    provide('managementCapacityEvaluationService', () => new ManagementCapacityEvaluationService());
    provide('approvalAgentService', () => new ApprovalAgentService());
    // jhipster-needle-add-entity-service-to-entities-component - JHipster will import entities services here
  },
});
