export enum ReturnsStatus {
  NOT_STARTED = 'NOT_STARTED',

  COMPLETE_AHEAD_OF_SCHEDULE = 'COMPLETE_AHEAD_OF_SCHEDULE',

  NORMAL_PROGRESS_INCOMPLETE = 'NORMAL_PROGRESS_INCOMPLETE',

  NORMAL_PROGRESS_COMPLETED = 'NORMAL_PROGRESS_COMPLETED',

  DELAY_NOT_COMPLETED = 'DELAY_NOT_COMPLETED',

  DELAY_COMPLETED = 'DELAY_COMPLETED',

  REMINDER_NOT_COMPLETED = 'REMINDER_NOT_COMPLETED',

  REMINDER_HAS_COMPLETED = 'REMINDER_HAS_COMPLETED',
}
