package com.cvicse.jy1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommunicationFormDictionaryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunicationFormDictionaryAllPropertiesEquals(
        CommunicationFormDictionary expected,
        CommunicationFormDictionary actual
    ) {
        assertCommunicationFormDictionaryAutoGeneratedPropertiesEquals(expected, actual);
        assertCommunicationFormDictionaryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunicationFormDictionaryAllUpdatablePropertiesEquals(
        CommunicationFormDictionary expected,
        CommunicationFormDictionary actual
    ) {
        assertCommunicationFormDictionaryUpdatableFieldsEquals(expected, actual);
        assertCommunicationFormDictionaryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunicationFormDictionaryAutoGeneratedPropertiesEquals(
        CommunicationFormDictionary expected,
        CommunicationFormDictionary actual
    ) {
        assertThat(expected)
            .as("Verify CommunicationFormDictionary auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunicationFormDictionaryUpdatableFieldsEquals(
        CommunicationFormDictionary expected,
        CommunicationFormDictionary actual
    ) {
        assertThat(expected)
            .as("Verify CommunicationFormDictionary relevant properties")
            .satisfies(
                e -> assertThat(e.getCommunicationformname()).as("check communicationformname").isEqualTo(actual.getCommunicationformname())
            )
            .satisfies(
                e -> assertThat(e.getCommunicationformtype()).as("check communicationformtype").isEqualTo(actual.getCommunicationformtype())
            )
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunicationFormDictionaryUpdatableRelationshipsEquals(
        CommunicationFormDictionary expected,
        CommunicationFormDictionary actual
    ) {}
}
