package com.cvicse.jy1.domain;

import static com.cvicse.jy1.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ContractPaymentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractPaymentAllPropertiesEquals(ContractPayment expected, ContractPayment actual) {
        assertContractPaymentAutoGeneratedPropertiesEquals(expected, actual);
        assertContractPaymentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractPaymentAllUpdatablePropertiesEquals(ContractPayment expected, ContractPayment actual) {
        assertContractPaymentUpdatableFieldsEquals(expected, actual);
        assertContractPaymentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractPaymentAutoGeneratedPropertiesEquals(ContractPayment expected, ContractPayment actual) {
        assertThat(expected)
            .as("Verify ContractPayment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractPaymentUpdatableFieldsEquals(ContractPayment expected, ContractPayment actual) {
        assertThat(expected)
            .as("Verify ContractPayment relevant properties")
            .satisfies(e -> assertThat(e.getWorkbagid()).as("check workbagid").isEqualTo(actual.getWorkbagid()))
            .satisfies(e -> assertThat(e.getWorkbagname()).as("check workbagname").isEqualTo(actual.getWorkbagname()))
            .satisfies(e -> assertThat(e.getContractcode()).as("check contractcode").isEqualTo(actual.getContractcode()))
            .satisfies(e -> assertThat(e.getContractname()).as("check contractname").isEqualTo(actual.getContractname()))
            .satisfies(e -> assertThat(e.getPlanpaymentnode()).as("check planpaymentnode").isEqualTo(actual.getPlanpaymentnode()))
            .satisfies(
                e ->
                    assertThat(e.getPlanpaymentamount())
                        .as("check planpaymentamount")
                        .usingComparator(bigDecimalCompareTo)
                        .isEqualTo(actual.getPlanpaymentamount())
            )
            .satisfies(
                e ->
                    assertThat(e.getActualpaymentamount())
                        .as("check actualpaymentamount")
                        .usingComparator(bigDecimalCompareTo)
                        .isEqualTo(actual.getActualpaymentamount())
            )
            .satisfies(e -> assertThat(e.getPaymenttype()).as("check paymenttype").isEqualTo(actual.getPaymenttype()))
            .satisfies(e -> assertThat(e.getFinancialvoucherid()).as("check financialvoucherid").isEqualTo(actual.getFinancialvoucherid()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractPaymentUpdatableRelationshipsEquals(ContractPayment expected, ContractPayment actual) {}
}
