package com.cvicse.jy1.domain;

import static com.cvicse.jy1.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OtherPaymentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtherPaymentAllPropertiesEquals(OtherPayment expected, OtherPayment actual) {
        assertOtherPaymentAutoGeneratedPropertiesEquals(expected, actual);
        assertOtherPaymentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtherPaymentAllUpdatablePropertiesEquals(OtherPayment expected, OtherPayment actual) {
        assertOtherPaymentUpdatableFieldsEquals(expected, actual);
        assertOtherPaymentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtherPaymentAutoGeneratedPropertiesEquals(OtherPayment expected, OtherPayment actual) {
        assertThat(expected)
            .as("Verify OtherPayment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtherPaymentUpdatableFieldsEquals(OtherPayment expected, OtherPayment actual) {
        assertThat(expected)
            .as("Verify OtherPayment relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getRegistertime()).as("check registertime").isEqualTo(actual.getRegistertime()))
            .satisfies(e -> assertThat(e.getSubjectid()).as("check subjectid").isEqualTo(actual.getSubjectid()))
            .satisfies(e -> assertThat(e.getSubjectname()).as("check subjectname").isEqualTo(actual.getSubjectname()))
            .satisfies(
                e ->
                    assertThat(e.getPaymentamount())
                        .as("check paymentamount")
                        .usingComparator(bigDecimalCompareTo)
                        .isEqualTo(actual.getPaymentamount())
            )
            .satisfies(e -> assertThat(e.getContractcode()).as("check contractcode").isEqualTo(actual.getContractcode()))
            .satisfies(e -> assertThat(e.getContractname()).as("check contractname").isEqualTo(actual.getContractname()))
            .satisfies(e -> assertThat(e.getWbsid()).as("check wbsid").isEqualTo(actual.getWbsid()))
            .satisfies(e -> assertThat(e.getWbsname()).as("check wbsname").isEqualTo(actual.getWbsname()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtherPaymentUpdatableRelationshipsEquals(OtherPayment expected, OtherPayment actual) {
        assertThat(expected)
            .as("Verify OtherPayment relationships")
            .satisfies(e -> assertThat(e.getProjectwbs()).as("check projectwbs").isEqualTo(actual.getProjectwbs()))
            .satisfies(e -> assertThat(e.getContract()).as("check contract").isEqualTo(actual.getContract()))
            .satisfies(e -> assertThat(e.getSubject()).as("check subject").isEqualTo(actual.getSubject()));
    }
}
