package com.cvicse.jy1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RiskPossibilityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPossibilityAllPropertiesEquals(RiskPossibility expected, RiskPossibility actual) {
        assertRiskPossibilityAutoGeneratedPropertiesEquals(expected, actual);
        assertRiskPossibilityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPossibilityAllUpdatablePropertiesEquals(RiskPossibility expected, RiskPossibility actual) {
        assertRiskPossibilityUpdatableFieldsEquals(expected, actual);
        assertRiskPossibilityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPossibilityAutoGeneratedPropertiesEquals(RiskPossibility expected, RiskPossibility actual) {
        assertThat(expected)
            .as("Verify RiskPossibility auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPossibilityUpdatableFieldsEquals(RiskPossibility expected, RiskPossibility actual) {
        assertThat(expected)
            .as("Verify RiskPossibility relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPossibilityUpdatableRelationshipsEquals(RiskPossibility expected, RiskPossibility actual) {}
}
