package com.cvicse.jy1.domain;

import static com.cvicse.jy1.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SharePaymentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSharePaymentAllPropertiesEquals(SharePayment expected, SharePayment actual) {
        assertSharePaymentAutoGeneratedPropertiesEquals(expected, actual);
        assertSharePaymentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSharePaymentAllUpdatablePropertiesEquals(SharePayment expected, SharePayment actual) {
        assertSharePaymentUpdatableFieldsEquals(expected, actual);
        assertSharePaymentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSharePaymentAutoGeneratedPropertiesEquals(SharePayment expected, SharePayment actual) {
        assertThat(expected)
            .as("Verify SharePayment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSharePaymentUpdatableFieldsEquals(SharePayment expected, SharePayment actual) {
        assertThat(expected)
            .as("Verify SharePayment relevant properties")
            .satisfies(e -> assertThat(e.getPlanpaymentnode()).as("check planpaymentnode").isEqualTo(actual.getPlanpaymentnode()))
            .satisfies(
                e ->
                    assertThat(e.getPlanpaymentamount())
                        .as("check planpaymentamount")
                        .usingComparator(bigDecimalCompareTo)
                        .isEqualTo(actual.getPlanpaymentamount())
            )
            .satisfies(
                e ->
                    assertThat(e.getActualpaymentamount())
                        .as("check actualpaymentamount")
                        .usingComparator(bigDecimalCompareTo)
                        .isEqualTo(actual.getActualpaymentamount())
            )
            .satisfies(e -> assertThat(e.getPaymenttype()).as("check paymenttype").isEqualTo(actual.getPaymenttype()))
            .satisfies(e -> assertThat(e.getFinancialvoucherid()).as("check financialvoucherid").isEqualTo(actual.getFinancialvoucherid()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSharePaymentUpdatableRelationshipsEquals(SharePayment expected, SharePayment actual) {}
}
