package com.cvicse.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QualitymanagementWbsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualitymanagementWbsAllPropertiesEquals(QualitymanagementWbs expected, QualitymanagementWbs actual) {
        assertQualitymanagementWbsAutoGeneratedPropertiesEquals(expected, actual);
        assertQualitymanagementWbsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualitymanagementWbsAllUpdatablePropertiesEquals(QualitymanagementWbs expected, QualitymanagementWbs actual) {
        assertQualitymanagementWbsUpdatableFieldsEquals(expected, actual);
        assertQualitymanagementWbsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualitymanagementWbsAutoGeneratedPropertiesEquals(QualitymanagementWbs expected, QualitymanagementWbs actual) {
        assertThat(expected)
            .as("Verify QualitymanagementWbs auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualitymanagementWbsUpdatableFieldsEquals(QualitymanagementWbs expected, QualitymanagementWbs actual) {
        assertThat(expected)
            .as("Verify QualitymanagementWbs relevant properties")
            .satisfies(e -> assertThat(e.getWbsspare1()).as("check wbsspare1").isEqualTo(actual.getWbsspare1()))
            .satisfies(e -> assertThat(e.getWbsspare2()).as("check wbsspare2").isEqualTo(actual.getWbsspare2()))
            .satisfies(e -> assertThat(e.getWbsspare3()).as("check wbsspare3").isEqualTo(actual.getWbsspare3()))
            .satisfies(e -> assertThat(e.getWbsspare4()).as("check wbsspare4").isEqualTo(actual.getWbsspare4()))
            .satisfies(e -> assertThat(e.getWbsspare5()).as("check wbsspare5").isEqualTo(actual.getWbsspare5()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualitymanagementWbsUpdatableRelationshipsEquals(QualitymanagementWbs expected, QualitymanagementWbs actual) {
        assertThat(expected)
            .as("Verify QualitymanagementWbs relationships")
            .satisfies(e -> assertThat(e.getQualityobjectives()).as("check qualityobjectives").isEqualTo(actual.getQualityobjectives()))
            .satisfies(e -> assertThat(e.getQualityreturns()).as("check qualityreturns").isEqualTo(actual.getQualityreturns()))
            .satisfies(e -> assertThat(e.getUnQualityAudit()).as("check unQualityAudit").isEqualTo(actual.getUnQualityAudit()));
    }
}
