package com.cvicse.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResourcemanagementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcemanagementAllPropertiesEquals(Resourcemanagement expected, Resourcemanagement actual) {
        assertResourcemanagementAutoGeneratedPropertiesEquals(expected, actual);
        assertResourcemanagementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcemanagementAllUpdatablePropertiesEquals(Resourcemanagement expected, Resourcemanagement actual) {
        assertResourcemanagementUpdatableFieldsEquals(expected, actual);
        assertResourcemanagementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcemanagementAutoGeneratedPropertiesEquals(Resourcemanagement expected, Resourcemanagement actual) {
        assertThat(expected)
            .as("Verify Resourcemanagement auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcemanagementUpdatableFieldsEquals(Resourcemanagement expected, Resourcemanagement actual) {
        assertThat(expected)
            .as("Verify Resourcemanagement relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getStarttime()).as("check starttime").isEqualTo(actual.getStarttime()))
            .satisfies(e -> assertThat(e.getEndtime()).as("check endtime").isEqualTo(actual.getEndtime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcemanagementUpdatableRelationshipsEquals(Resourcemanagement expected, Resourcemanagement actual) {
        assertThat(expected)
            .as("Verify Resourcemanagement relationships")
            .satisfies(e -> assertThat(e.getWbs()).as("check wbs").isEqualTo(actual.getWbs()));
    }
}
