package com.cvicse.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RiskidentificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskidentificationAllPropertiesEquals(Riskidentification expected, Riskidentification actual) {
        assertRiskidentificationAutoGeneratedPropertiesEquals(expected, actual);
        assertRiskidentificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskidentificationAllUpdatablePropertiesEquals(Riskidentification expected, Riskidentification actual) {
        assertRiskidentificationUpdatableFieldsEquals(expected, actual);
        assertRiskidentificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskidentificationAutoGeneratedPropertiesEquals(Riskidentification expected, Riskidentification actual) {
        assertThat(expected)
            .as("Verify Riskidentification auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskidentificationUpdatableFieldsEquals(Riskidentification expected, Riskidentification actual) {
        assertThat(expected)
            .as("Verify Riskidentification relevant properties")
            .satisfies(e -> assertThat(e.getProjectname()).as("check projectname").isEqualTo(actual.getProjectname()))
            .satisfies(e -> assertThat(e.getYear()).as("check year").isEqualTo(actual.getYear()))
            .satisfies(e -> assertThat(e.getNodename()).as("check nodename").isEqualTo(actual.getNodename()))
            .satisfies(e -> assertThat(e.getRisktype()).as("check risktype").isEqualTo(actual.getRisktype()))
            .satisfies(e -> assertThat(e.getDecumentid()).as("check decumentid").isEqualTo(actual.getDecumentid()))
            .satisfies(e -> assertThat(e.getVersion()).as("check version").isEqualTo(actual.getVersion()))
            .satisfies(e -> assertThat(e.getUsetime()).as("check usetime").isEqualTo(actual.getUsetime()))
            .satisfies(e -> assertThat(e.getSystemlevel()).as("check systemlevel").isEqualTo(actual.getSystemlevel()))
            .satisfies(e -> assertThat(e.getRisklevel()).as("check risklevel").isEqualTo(actual.getRisklevel()))
            .satisfies(e -> assertThat(e.getLimitationtime()).as("check limitationtime").isEqualTo(actual.getLimitationtime()))
            .satisfies(e -> assertThat(e.getClosetype()).as("check closetype").isEqualTo(actual.getClosetype()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskidentificationUpdatableRelationshipsEquals(Riskidentification expected, Riskidentification actual) {
        assertThat(expected)
            .as("Verify Riskidentification relationships")
            .satisfies(e -> assertThat(e.getCreatorid()).as("check creatorid").isEqualTo(actual.getCreatorid()))
            .satisfies(e -> assertThat(e.getResponsibleid()).as("check responsibleid").isEqualTo(actual.getResponsibleid()))
            .satisfies(e -> assertThat(e.getAuditorid()).as("check auditorid").isEqualTo(actual.getAuditorid()));
    }
}
