package com.cvicse.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SecrecymanagementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecrecymanagementAllPropertiesEquals(Secrecymanagement expected, Secrecymanagement actual) {
        assertSecrecymanagementAutoGeneratedPropertiesEquals(expected, actual);
        assertSecrecymanagementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecrecymanagementAllUpdatablePropertiesEquals(Secrecymanagement expected, Secrecymanagement actual) {
        assertSecrecymanagementUpdatableFieldsEquals(expected, actual);
        assertSecrecymanagementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecrecymanagementAutoGeneratedPropertiesEquals(Secrecymanagement expected, Secrecymanagement actual) {
        assertThat(expected)
            .as("Verify Secrecymanagement auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecrecymanagementUpdatableFieldsEquals(Secrecymanagement expected, Secrecymanagement actual) {
        assertThat(expected)
            .as("Verify Secrecymanagement relevant properties")
            .satisfies(e -> assertThat(e.getSecrecyid()).as("check secrecyid").isEqualTo(actual.getSecrecyid()))
            .satisfies(e -> assertThat(e.getPublishedby()).as("check publishedby").isEqualTo(actual.getPublishedby()))
            .satisfies(e -> assertThat(e.getDocumentname()).as("check documentname").isEqualTo(actual.getDocumentname()))
            .satisfies(e -> assertThat(e.getDocumenttype()).as("check documenttype").isEqualTo(actual.getDocumenttype()))
            .satisfies(e -> assertThat(e.getDocumentsize()).as("check documentsize").isEqualTo(actual.getDocumentsize()))
            .satisfies(e -> assertThat(e.getSecretlevel()).as("check secretlevel").isEqualTo(actual.getSecretlevel()))
            .satisfies(e -> assertThat(e.getAuditStatus()).as("check auditStatus").isEqualTo(actual.getAuditStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecrecymanagementUpdatableRelationshipsEquals(Secrecymanagement expected, Secrecymanagement actual) {
        assertThat(expected)
            .as("Verify Secrecymanagement relationships")
            .satisfies(e -> assertThat(e.getCreatorid()).as("check creatorid").isEqualTo(actual.getCreatorid()))
            .satisfies(e -> assertThat(e.getAuditorid()).as("check auditorid").isEqualTo(actual.getAuditorid()));
    }
}
