package com.cvicse.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TechnicalmanagementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalmanagementAllPropertiesEquals(Technicalmanagement expected, Technicalmanagement actual) {
        assertTechnicalmanagementAutoGeneratedPropertiesEquals(expected, actual);
        assertTechnicalmanagementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalmanagementAllUpdatablePropertiesEquals(Technicalmanagement expected, Technicalmanagement actual) {
        assertTechnicalmanagementUpdatableFieldsEquals(expected, actual);
        assertTechnicalmanagementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalmanagementAutoGeneratedPropertiesEquals(Technicalmanagement expected, Technicalmanagement actual) {
        assertThat(expected)
            .as("Verify Technicalmanagement auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalmanagementUpdatableFieldsEquals(Technicalmanagement expected, Technicalmanagement actual) {
        assertThat(expected)
            .as("Verify Technicalmanagement relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getStarttime()).as("check starttime").isEqualTo(actual.getStarttime()))
            .satisfies(e -> assertThat(e.getEndtime()).as("check endtime").isEqualTo(actual.getEndtime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalmanagementUpdatableRelationshipsEquals(Technicalmanagement expected, Technicalmanagement actual) {
        assertThat(expected)
            .as("Verify Technicalmanagement relationships")
            .satisfies(e -> assertThat(e.getWbs()).as("check wbs").isEqualTo(actual.getWbs()));
    }
}
