import { defineComponent, provide } from 'vue';

import OfficersService from './officers/officers.service';
import DepartmentService from './department/department.service';
import ProjectpbsService from './projectpbs/projectpbs.service';
import ProjectwbsService from './projectwbs/projectwbs.service';
import RoleService from './role/role.service';
import PermissionService from './permission/permission.service';
import DocumentService from './document/document.service';
import ProgressPlanService from './progress-plan/progress-plan.service';
import PlanReturnsService from './plan-returns/plan-returns.service';
import ContractService from './contract/contract.service';
import QualityObjectivesService from './quality-objectives/quality-objectives.service';
import QualityReturnsService from './quality-returns/quality-returns.service';
import UnQualityAuditService from './un-quality-audit/un-quality-audit.service';
import TechnicalConditionService from './technical-condition/technical-condition.service';
import ProjectRiskService from './project-risk/project-risk.service';
import RiskReportService from './risk-report/risk-report.service';
import DocumentmenuService from './documentmenu/documentmenu.service';
import LeaveApplicationInfoService from './leave-application-info/leave-application-info.service';
import HrManagementService from './hr-management/hr-management.service';
import FrontlineService from './frontline/frontline.service';
import EventsService from './events/events.service';
import ArchivesService from './archives/archives.service';
import ProjectdeliverablesService from './projectdeliverables/projectdeliverables.service';
import DeliverablesService from './deliverables/deliverables.service';
import WorkbagService from './workbag/workbag.service';
import WorkService from './work/work.service';
import SubjectService from './subject/subject.service';
import SubjectCostBudgetService from './subject-cost-budget/subject-cost-budget.service';
import ProjectBudgetService from './project-budget/project-budget.service';
import OutsourcingContractService from './outsourcing-contract/outsourcing-contract.service';
import DeliveryContentService from './delivery-content/delivery-content.service';
import MilestoneNodeService from './milestone-node/milestone-node.service';
import PaymentApplicationService from './payment-application/payment-application.service';
import TransactionPaymentService from './transaction-payment/transaction-payment.service';
import SporadicPurchasePaymentService from './sporadic-purchase-payment/sporadic-purchase-payment.service';
import SharePaymentService from './share-payment/share-payment.service';
import ContractPaymentService from './contract-payment/contract-payment.service';
import PaymentCostListService from './payment-cost-list/payment-cost-list.service';
import FundSourceListService from './fund-source-list/fund-source-list.service';
import QualityObjectivesDictionaryService from './quality-objectives-dictionary/quality-objectives-dictionary.service';
import QualityPlanService from './quality-plan/quality-plan.service';
import RegularInspectionService from './regular-inspection/regular-inspection.service';
import KeyNodeInspectionService from './key-node-inspection/key-node-inspection.service';
import QualitytozeroService from './qualitytozero/qualitytozero.service';
import DeviationPermitApplicationService from './deviation-permit-application/deviation-permit-application.service';
import CommunicationPlanService from './communication-plan/communication-plan.service';
import CommunicationRecordService from './communication-record/communication-record.service';
import CommunicationDictionaryService from './communication-dictionary/communication-dictionary.service';
import CommunicationFormDictionaryService from './communication-form-dictionary/communication-form-dictionary.service';
import LetterService from './letter/letter.service';
import CustomerSatisfactionService from './customer-satisfaction/customer-satisfaction.service';
import RiskPossibilityService from './risk-possibility/risk-possibility.service';
import RiskTypeService from './risk-type/risk-type.service';
import RiskLevelService from './risk-level/risk-level.service';
import SystemLevelService from './system-level/system-level.service';
import RiskReturnService from './risk-return/risk-return.service';
import UserService from '@/entities/user/user.service';
// jhipster-needle-add-entity-service-to-entities-component-import - JHipster will import entities services here

export default defineComponent({
  compatConfig: { MODE: 3 },
  name: 'Entities',
  setup() {
    provide('userService', () => new UserService());
    provide('officersService', () => new OfficersService());
    provide('departmentService', () => new DepartmentService());
    provide('projectpbsService', () => new ProjectpbsService());
    provide('projectwbsService', () => new ProjectwbsService());
    provide('roleService', () => new RoleService());
    provide('permissionService', () => new PermissionService());
    provide('documentService', () => new DocumentService());
    provide('progressPlanService', () => new ProgressPlanService());
    provide('planReturnsService', () => new PlanReturnsService());
    provide('contractService', () => new ContractService());
    provide('qualityObjectivesService', () => new QualityObjectivesService());
    provide('qualityReturnsService', () => new QualityReturnsService());
    provide('unQualityAuditService', () => new UnQualityAuditService());
    provide('technicalConditionService', () => new TechnicalConditionService());
    provide('projectRiskService', () => new ProjectRiskService());
    provide('riskReportService', () => new RiskReportService());
    provide('documentmenuService', () => new DocumentmenuService());
    provide('leaveApplicationInfoService', () => new LeaveApplicationInfoService());
    provide('hrManagementService', () => new HrManagementService());
    provide('frontlineService', () => new FrontlineService());
    provide('eventsService', () => new EventsService());
    provide('archivesService', () => new ArchivesService());
    provide('projectdeliverablesService', () => new ProjectdeliverablesService());
    provide('deliverablesService', () => new DeliverablesService());
    provide('workbagService', () => new WorkbagService());
    provide('workService', () => new WorkService());
    provide('subjectService', () => new SubjectService());
    provide('subjectCostBudgetService', () => new SubjectCostBudgetService());
    provide('projectBudgetService', () => new ProjectBudgetService());
    provide('outsourcingContractService', () => new OutsourcingContractService());
    provide('deliveryContentService', () => new DeliveryContentService());
    provide('milestoneNodeService', () => new MilestoneNodeService());
    provide('paymentApplicationService', () => new PaymentApplicationService());
    provide('transactionPaymentService', () => new TransactionPaymentService());
    provide('sporadicPurchasePaymentService', () => new SporadicPurchasePaymentService());
    provide('sharePaymentService', () => new SharePaymentService());
    provide('contractPaymentService', () => new ContractPaymentService());
    provide('paymentCostListService', () => new PaymentCostListService());
    provide('fundSourceListService', () => new FundSourceListService());
    provide('qualityObjectivesDictionaryService', () => new QualityObjectivesDictionaryService());
    provide('qualityPlanService', () => new QualityPlanService());
    provide('regularInspectionService', () => new RegularInspectionService());
    provide('keyNodeInspectionService', () => new KeyNodeInspectionService());
    provide('qualitytozeroService', () => new QualitytozeroService());
    provide('deviationPermitApplicationService', () => new DeviationPermitApplicationService());
    provide('communicationPlanService', () => new CommunicationPlanService());
    provide('communicationRecordService', () => new CommunicationRecordService());
    provide('communicationDictionaryService', () => new CommunicationDictionaryService());
    provide('communicationFormDictionaryService', () => new CommunicationFormDictionaryService());
    provide('letterService', () => new LetterService());
    provide('customerSatisfactionService', () => new CustomerSatisfactionService());
    provide('riskPossibilityService', () => new RiskPossibilityService());
    provide('riskTypeService', () => new RiskTypeService());
    provide('riskLevelService', () => new RiskLevelService());
    provide('systemLevelService', () => new SystemLevelService());
    provide('riskReturnService', () => new RiskReturnService());
    // jhipster-needle-add-entity-service-to-entities-component - JHipster will import entities services here
  },
});
